### ISSUE TITLE
Use IEntityTypeConfiguration

### ISSUE THREAD

**Issue by totpero** [Dorset-Council-UK/GIFramework-Maps#188]
Hi,
In ef-core-6.0 release, is new feature EntityTypeConfiguration:  https://github.com/dotnet/efcore/issues/23163
You can read more here https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/whatsnew#entitytypeconfigurationattribute
For more clean code you can use for example like this:

```
public class LayerConfiguration : IEntityTypeConfiguration<Layer>
{
    public void Configure(EntityTypeBuilder<Layer> builder)
    {
           builder.ToTable(GIFrameworkMapsDbProperties.DbTablePrefix + "Layers", GIFrameworkMapsDbProperties.DbSchema);

            builder.Property(x => x.ApplicationName)......
           .......
    }
}

I think is more clean code like this.
If you want I can try to do this.

**Comment by RobQuincey-DC** [comment]
I'd be happy for you to try this. It looks like it could be an improvement, but just for my own peace of mind, if you initially just apply it to a single entity/class whatever and open a draft PR so we can see what it does and what the improvements are that would be ideal!

**Comment by totpero** [comment]
Hi @RobQuincey-DC ,
I just add sample commit with two Entity configurations .
What is the benefits:

1. If the project use IEntityTypeConfiguration for the entities, this create separate level for database entities configurations centralized;
2. All the entities can be cleaned without any database attributes.
3. If you are using IEntityTypeConfiguration is more easily to migrate database provider. Ex from postgress to mssql.
4. Is not ok to use the entities models to MVC views, you need to create ViewModels and remove all the entities validation attributes like: ` [Display(Name = "Version Notes (optional)"), MaxLength(500)]` or` [Required]` and move this attributes to viewmodels.
5. more other benefits...

**Comment by RobQuincey-DC** [comment]
@totpero I like this, thanks for putting a sample together. As the project has grown bigger I can see how having the entities configured in a single location makes life easier, particularly since some parts are in data annotations and others in the OnModelCreating. This should help bring that together a bit more.

Not gonna lie, this won't be a high priority for one of us to do, so if you want to continue with it we would be more than happy to accept a working pull request with these changes.
