### ISSUE TITLE
Metadata not being pulled through on info window

### ISSUE THREAD

**Issue by VulpesFerrilata** [Dorset-Council-UK/GIFramework-Maps#199]
When clicking on the info button next to a layer to bring up more information about it, the descriptions and keywords are not being pulled through. Instead you get the default text of 'No description provided'.

This is happening to most but not all layers. For an example that is working correctly, check the 'Provisional addresses' layer.

![image](https://github.com/Dorset-Council-UK/GIFramework-Maps/assets/114388582/5ecec7e5-7366-4193-924f-3b6ce3d3dea6)

**Comment by RobQuincey-DC** [comment]
This is due to these layers being in a workspace which contains underscore characters, which causes the CSW metadata call to throw an exception. The resolution is to remove the CSW metadata link or rename the workspace.

Ideally this should detect if the CSW metadata fails with an exception then fall back to another method, such as using the GetCapabilities.

**Comment by VulpesFerrilata** [comment]
Ahhh of course. The workspace names will be fixed as and when we migrate data so this will be an ongoing fix. I'm happy to keep an eye on this and keep track of anything that will need fixing separately.
