### ISSUE TITLE
Add attribution details on layer metadata

### ISSUE THREAD

**Issue by VulpesFerrilata** [Dorset-Council-UK/GIFramework-Maps#208]
We record attributions for layers but are currently not displaying them anywhere. Can we add in attributions/copyright information on the layer information button? 
![image](https://github.com/Dorset-Council-UK/GIFramework-Maps/assets/114388582/1165a30a-070a-45ae-a79a-f8ba820618ee)

I'm thinking here, in the area highlighted in yellow:
![image](https://github.com/Dorset-Council-UK/GIFramework-Maps/assets/114388582/afe673ed-b38b-429c-a150-10eb6c8ea192)

**Comment by paul-dorsetcouncil** [comment]
+1 from me although I thought we were displaying them unless it failed to read from the CSW service but @RobQuincey-DC can no doubt confirm. 

I definitely think we should be displaying it and that the abstracts should be informative. I note that the one in the screenshot is a bad example as ideally the abstract would not just be the name of the layer repeated but rather a description of what the layer is and it's intended purpose. 

So perhaps that should read:
"Shows the locations of all registered schools within Dorset along with information about about each school. Please include copyright statement if using in a publication."

**Comment by RobQuincey-DC** [comment]
Attribution information is not pulled direct from the source into the metadata viewer at the moment. We do display attributions for layers in the bottom right, but these are pulled from a database table rather than the source. We keep these in a database rather than relying on fetching metadata from the layer source for two main reasons:

- Speed - retrieving individual attribution information from every layer is dependent on the speed of the web server, so can be slow
- Availability - from experience, many services simply do not provide attribution information or it is wrong. Some types of layer (such as XYZ layers) do not even have this capability

What we do do, is when an admin uses the layer wizard, we check the attribution provided by the source and compare it with the database, which then gives the user the best match. This is detailed in PR #155 

It would probably make sense to add the source provided attribution into the metadata viewer, as it may provide more information that the database supplied one (but in most cases, it will just be the same).

And yes, that's a poorly described layer, but that's a data issue, not an application issue.

**Comment by VulpesFerrilata** [comment]
Thanks for the explanation @RobQuincey-DC  - I wasn't quite sure how the copyrights in the bottom-right corner worked.

I'll have a go at pulling the attribution through into the metadata viewer. I raised this an an issue as I've been working with our flooding team on a version that contains a mix of layers from different sources, and they had asked how they could tell where each layer was sourced from.
